Abteilung:
  FuzzySearch:
    preloaderMarkup: '<div class="pswp__preloader__icn"><div class="pswp__preloader__cut"><div class="pswp__preloader__donut"></div></div></div>'
    bgOpacity: 0.8
    alwaysInclude: false
    selector:
      onDocument: '[instanceof Abteilung.FuzzySearch:Include]'
      collection: '[instanceof Neos.Neos:ContentCollection]'
      content: '[instanceof Abteilung.FuzzySearch:Include],[instanceof Abteilung.FuzzySearch:SearchBoxMixin][searchbox=true]'
      lightbox: .lightbox
      gallery: body


Carbon:
  IncludeAssets:
    Packages:
      zzz_AbteilungFuzzySearch:
        Package: 'Abteilung.FuzzySearch'
        ConditionPrototype: 'Abteilung.FuzzySearch:IncludeCase'
        Path:
          File:
            CSS: 'Public'
            JS: 'Public'
        Live:
          # Dark.css and Light.css are included Themes
          Head:
            - Dark.css[async]
            - Main.js[defer]


Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Abteilung.FuzzySearch:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Abteilung.FuzzySearch: true